# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kc_bRP72pnm84r0s6wB_636Ymxh3H6Ss
"""

!pip install selenium
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin
import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
from selenium import webdriver
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
wd = webdriver.Chrome('chromedriver',chrome_options=chrome_options)

import time
from selenium import webdriver
from selenium.webdriver import Chrome
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome import service as fs
#from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

data=[]
wait = WebDriverWait(wd,15)
wd.get("https://www.youtube.com/watch?v=xJXD2BXorl4") 

#THIS IS THE SAME BUT SHOULD BE INDENTED UNDER WITH TO WORK ON YOUR OWN COMPUTER
for item in range(100): 
 wait.until(EC.visibility_of_element_located((By.TAG_NAME, "body"))).send_keys(Keys.END) 
#time.sleep(30)

for comment in wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, "#content"))):
  data.append(comment.text)

import pandas as pd   
df = pd.DataFrame(data, columns=['comment'])
df.info()
df.head()

import csv
#header = ['ID', 'num']
body = [df]

with open('RFA.csv', 'w') as f:
 
  writer = csv.writer(f)
  writer.writerows(body)

f.close()

import spacy
file = pd.read_csv("RFA.csv")

!pip install fugashi[unidic-lite]

import fugashi

tagger = fugashi.Tagger()


words = [word.surface for word in tagger(file)]
print(*words)
print("input:", file.head())
for word in tagger(file):
    print(word.surface, word.feature.lemma, sep="\t")